<?php

/**
 * @file
 * Contains visualnet_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function visualnet_api_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the visualnet_api module.
        case 'help.page.visualnet_api':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Visualnet client REST API') . '</p>';
            return $output;

        default:
    }
}

/**
 * Implements hook_theme().
 */
function visualnet_api_theme() {
return [
    'test' => [
      'variables' => [
        'data' => NULL
      ],
    ]
  ];
}
